### ISSUE TITLE
make error  

### ISSUE THREAD

**Issue by chunxue-ding** [objectcomputing/mFAST#103]
$ mkdir build
$ cd build
$ cmake ..
$ make
...
Scanning dependencies of target mfast_test
[ 53%] Building CXX object tests/CMakeFiles/mfast_test.dir/test_main.cpp.o
 fatal error: catch.hpp: No such file or directory

**Comment by ksergey** [comment]
You forgot to checkout submodules.

`git submodule update --init --recursive`

**Comment by chunxue-ding** [comment]
thank you for you advices.
