### ISSUE TITLE
avoid "std::pow(10,x)"?

### ISSUE THREAD

**Issue by javapowered** [objectcomputing/mFAST#30]
Please consider this as a very low priority feature request, but let me post it, as performance is important part of mfast :)

I've found such code:

     operator double()
      {
        double x = mantissa();
        return x * std::pow(10, exponent());
      }

Of course it should be tested, but likely something like this must be significantly faster:

	int pow10[] = {
                0.0000000001,
                0.000000001,
                0.00000001,
                0.0000001,
                0.000001,
                0.00001,
                0.0001,
                0.001,
                0.01,
                0.1,
		1,
		10,
		100,
		1000,
		10000,
		100000,
		1000000,
		10000000,
		100000000,
		1000000000,
	};

     operator double()
      {
        double x = mantissa();
        return x * pow10[exponent() + 10];
      }

**Comment by huangminghuang** [comment]
The code uses boost::x3::extension::scale() instead of std::pow() now.
