### ISSUE TITLE
error: wrong number of template arguments (11, should be 10)

### ISSUE THREAD

**Issue by vm2002** [objectcomputing/mFAST#34]
Hi,

The boost::tuple implementation currently supports tuples with up to 10 elements. The generated code does not compile:

struct  templates_description
  : mfast::templates_description
{
  typedef boost::tuple<EMDPacketHeader,
                       Beacon,
                       ProductStateChange,
                       MassInstrumentStateChange,
                       InstrumentStateChange,
                       DepthIncremental,
                       ComplexInstrumentUpdate,
                       QuoteRequest,
                       CrossRequest,
                       DepthSnapshot,
                       TopOfBookImplied> types;
  templates_description();
  static const templates_description* instance();
};

Is there any work around for this limitation in mFAST?

Thanks

**Comment by huangminghuang** [comment]
I have replaced boost::tuple with std::tuple which should fix you problem.
