### ISSUE TITLE
Error while processing presence map inside optional group

### ISSUE THREAD

**Issue by uncle-f** [objectcomputing/mFAST#36]
mFast fails to decode EUREX Reference Data stream.

Running sample data with the appropriate XML template gives the following error:

./performance_test/mf_generic_decode -t ../example.xml -f ./example.dat
/opt/mfast/src/mfast/coder/decoder/fast_istream.h(324): Throw in function typename boost::enable_if<boost::is_integral<T>, bool>::type mfast::fast_istream::decode(T&, bool) [with T = int]
Dynamic exception type: boost::exception_detail::clone_impl<mfast::fast_dynamic_error>
std::exception::what: std::exception
[mfast::tag_error_code*] = D2

We have a suspicion that the optional groups which are present in the XML template are processed incorrectly. The debug output shows that mFast tries to decode 0xC0 byte as a value of the field called "TransactTime", whereas 0xC0 in this case is a presence map inside the group called "ComplexInstrumentDescriptorGroup".

Below is the link to the message example and the XML templates.

https://www.dropbox.com/s/zoxs4p5aykx7qp0/mfastBug.zip?dl=0

**Comment by huangminghuang** [comment]
fixed in commit 9ec02ec4f4fd2614b8e5056443963b28559bb91c
