### ISSUE TITLE
Build mFAST with project?

### ISSUE THREAD

**Issue by ksergey** [objectcomputing/mFAST#49]
Hi,

It's possible to build mFAST library during build a cmake-project?

for example, something like this:
```cmake
...
set( mFast_build_examples OFF )
set( mFast_build_test OFF )
include( external/mFAST/mFAST.cmake )
...
```

Thanks

**Comment by falanger** [comment]
Hi, @ksergey! Yes, it's possible:
For example, you may directly include mFAST to your project:
```cmake
set( mFast_build_examples OFF CACHE BOOL "disable examples" )
set( mFast_build_test OFF CACHE BOOL "disable tests" )
add_subdirectory("${CMAKE_CURRENT_SOURCE_DIR}/external/mFAST")
```
Also you may include mFAST as downloadable external project (follow this snippet: https://gist.github.com/oneamtu/3734295)

**Comment by ksergey** [comment]
@falanger thanks!
