### ISSUE TITLE
failed to compile

### ISSUE THREAD

**Issue by ksergey** [objectcomputing/mFAST#54]
Hello,

failed to compile mfast with gcc 6.1.1:
`/home/ksergey/dev/astsff/external/mFAST/src/mfast/coder/decoder_v2/fast_decoder_core.h:110:35: error: return-statement with 
a value, in function returning 'void' [-fpermissive]
   void get_token() const { return current_token_; }
                                   ^~~~~~~~~~~~~~
`

gcc -v
`└─[10:18]$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/6.1.1/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --enable-libmpx --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --disable-multilib --disable-werror --enable-checking=release
Thread model: posix
gcc version 6.1.1 20160602 (GCC)
`

**Comment by huangminghuang** [comment]
fixed in commit 373a8f73d39e164dd12483222b5f0973e562c392
