### ISSUE TITLE
mFAST overwrites language version and thus breaks build

### ISSUE THREAD

**Issue by AlexeyDmitriev** [objectcomputing/mFAST#58]
Consider small project

CMakeLists.txt
```
cmake_minimum_required(VERSION 2.8)

find_package(mFAST)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++14")
add_executable(a a.cpp)
//...some targets that use mFAST
```

a.cpp
```
auto f(int a, int b) { // requires c++14
	return a + b;
}

int main() {
	return 0;
}
```

So when I make it, I got compilation error because compilation string is
`/usr/bin/c++     -std=c++14   -std=c++11 -o CMakeFiles/a.dir/a.cpp.o -c PATH/a.cpp`
--std=c++11 is from `lib/cmake/mFAST/mFASTConfig.cmake`

I propose not to use `add_definitions` here and require user to choose appropriate version

**Comment by AlexeyDmitriev** [comment]
[Possible fix](https://github.com/AlexeyDmitriev/mFAST/tree/do_not_force_cpp11)

**Comment by huangminghuang** [comment]
with commit c9f9a1575d97721e450be7c60ba0631a0312b03d, you can override the c++ standard flag as follows:
  cmake -DCMAKE_CXX_STANDARD=14
