### ISSUE TITLE
Null fields with No Operator and optional not encoded correctly. 

### ISSUE THREAD

**Issue by LarsMattsson** [objectcomputing/mFAST#59]
When having no operator and optional field the specification says this for null fields:
"If a field is optional and has no field operator, it is encoded with a nullable representation and the NULL is used to represent absence of a value. It will not occupy any bits in the presence map. "

When trying this out I found that the "No operator" + Optional is not encoded correctly. They are not written to the stream at all.

After some digging I found that the fast_encoder.cpp is skipping these since marked as absent and the encoder_field_operator is encoding them incorrect.  

This is a first suggestion what needs to be done: 

in 
encoder_field_operator.cpp these lines where added\changed to the  encode_impl for the no_operator.
      if (cref.absent()) 
      {
          stream.encode_null();
      }
      else
      {
          stream << cref;
      }

in the fast_encoder.cpp for the fast_encoder_impl::visit(message_cref cref, bool force_reset) {
the vistior also now visit fields with operator none even if not present. 

  for (auto &&field : message)
    if (field.present() || field.instruction()->field_operator() == operator_none)
      apply_accessor(*this, field);

**Comment by huangminghuang** [comment]
The issue is fixed by Pull Request #60
