### ISSUE TITLE
Build error - missing tinyxml

### ISSUE THREAD

**Issue by v-instrumentix** [objectcomputing/mFAST#61]
$ !2046
git clone https://github.com/objectcomputing/mFAST.git
Initialized empty Git repository in /work/src/mFAST/.git/
remote: Counting objects: 6197, done.
remote: Total 6197 (delta 0), reused 0 (delta 0), pack-reused 6197
Receiving objects: 100% (6197/6197), 2.43 MiB | 2.41 MiB/s, done.
Resolving deltas: 100% (4714/4714), done.
$ cd mFAST
$ mkdir build
$ cd build/
$ ../../e cmake -DCMAKE_INSTALL_PREFIX=/work -DCMAKE_BUILD_TYPE=Release -DBOOST_ROOT=/work -DCMAKE_C_FLAGS="-Wall -O3 -m64 -fPIC" -DCMAKE_CXX_FLAGS="-Wall -O3 -m64 -fPIC -std=gnu++11 -static-libgcc -static-libstdc++" ..
-- The CXX compiler identification is GNU 4.9.3
-- Check for working CXX compiler: /work/bin/g++
-- Check for working CXX compiler: /work/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Boost version: 1.58.0
-- Configuring done
CMake Error at src/mfast/xml_parser/CMakeLists.txt:13 (add_library):
  Cannot find source file:

    /work/src/mFAST/src/mfast/xml_parser/../../../tinyxml2/tinyxml2.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx

CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_C_FLAGS

-- Build files have been written to: /work/src/mFAST/build

**Comment by huangminghuang** [comment]
Use "git clone --recursive" as describe in the README.md

**Comment by v-instrumentix** [comment]
My bad, missed it.

Thanks so much!
