### ISSUE TITLE
Memory overwritten when creating templates definitions

### ISSUE THREAD

**Issue by LarsMattsson** [objectcomputing/mFAST#62]
hello, 

Using the olso cash [FASTMessageConfig.xml](http://www.oslobors.no/ob_eng/obnewsletter/download/4dca4e1275f3f60d90c6507c3f822902/file/file/FASTMsgConfig.xml) 
the templates_builder::VisitExit writes outside the allocated memory

the code here: the this->num_instuctions() returns 16 while the templates is 27 entries. 
In the best case it´s only overwrites the arena_allocator already allocated memory, making it not possible to load a second template (using the same template_registry). But since it´s the last thing allocated normally not an big issue. 
In worse case it writes outside the allocated memory (not the case with the olso cash template) 

`
bool templates_builder::VisitExit(const XMLElement &element) {
  if (std::strcmp(element.Name(), "templates") == 0) {
    typedef const template_instruction *const_template_instruction_ptr_t;

    definition_->instructions_ = new (alloc())
        const_template_instruction_ptr_t[this->num_instructions()];
    std::copy(templates_.begin(), templates_.end(), definition_->instructions_);
    definition_->instructions_count_ = static_cast<uint32_t>(templates_.size());
  }
  return true;
}`

Should the definition_->instructions_ not be the size of the templates? 

added a modified version of dictionary_builder_test.cpp where it tries to print all the templates names. it crashes.  (The test requites the dummy.xml (in the tests.zip file) plus the FASTMessageConfig.xml to work)

[tests.zip](https://github.com/objectcomputing/mFAST/files/536082/tests.zip)

**Comment by LarsMattsson** [comment]
Failed to upload the new dictonary_builder_test.cpp as well as the dummy.xml file. 
[tests.zip](https://github.com/objectcomputing/mFAST/files/536080/tests.zip)

**Comment by huangminghuang** [comment]
Fixed in commit 08e3a186c62e395b0a02dad780b08f43a2f4907b
