### ISSUE TITLE
Dynamically reading templates in multiple threads does not work. Please add lock around tinyxml

### ISSUE THREAD

**Issue by LarsMattsson** [objectcomputing/mFAST#66]
Dynamically reading templates in multiple threads does not work. 

Would it be possible to add a lock in the dynamic_templates_description::dynamic_templates_description function? 

Or at least write it as a limitation that you need to have a look around the dynamic_templates_description::dynamic_templates_description(    const char *xml_content, const char *cpp_ns, template_registry *registry) 
function for it not to crash.

**Comment by huangminghuang** [comment]
The parameter template_registry allows you to control the scope of resource dynamic_templates_description uses. If you need to parse unrelated templates from different threads, you should use the thread_local copy of template_registry for the job. Here is the example,

thread_local static template_registry thread_local_registry;
dynamic_templates_description mydesc(xml, "myns", &thread_local_registry);
