### ISSUE TITLE
Build errors on VS2013

### ISSUE THREAD

**Issue by lxuc** [objectcomputing/mFAST#75]
Hi, I build mfast on windows with cmake and vs2013.
The project was created successfully, then I start build ALL_BUILD project and got following errors:
2>E:\projects\mFAST\src\mfast/value_storage.h(122): error C2535: 'std::enable_if<B,T>::type mfast::value_storage::get(void) const' : member function already defined or declared
1>E:\projects\mFAST\src\mfast/value_storage.h(122): error C2535: 'std::enable_if<B,T>::type mfast::value_storage::get(void) const' : member function already defined or declared
1>          E:\projects\mFAST\src\mfast/value_storage.h(115) : see declaration of 'mfast::value_storage::get'

The error shows the following two funtions were already defined or declared:
#if SIZEOF_VOID_P == 4
  template <typename T>
  enable_if_t<std::is_integral<T>::value && (sizeof(T) <= 4)> set(T v) {
    of_uint32.content_ = static_cast<uint32_t>(v);
  }

  template <typename T>
  enable_if_t<std::is_integral<T>::value && (sizeof(T) > 4)> set(T v) {
    of_uint64.content_ = static_cast<uint64_t>(v);
  }
#else

I also got 57 errors of this type. How to resolve this problem?
Thanks in advance.

**Comment by huangminghuang** [comment]
The master branch works fine for Visual Studio 2013/2015 on the AppVeyor CI service (https://ci.appveyor.com/project/huangminghuang/mfast). Try to see if there is any inconsistency between your environment and AppVeyor setup.
