### ISSUE TITLE
Cannot build shared libraries

### ISSUE THREAD

**Issue by lxuc** [objectcomputing/mFAST#76]
I built mFAST and generated static libraries successfully with default configuration with VS2013 update 5 
But when I enabled BUILD_SHARED_LIBS in CMake to build shared libraries. I got two link errors as below:

18>fixed_template_test_v2.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __thiscall mfast::coder::fast_decoder_base::fast_decoder_base(class mfast::allocator *)" (__imp_??0fast_decoder_base@coder@mfast@@QAE@PAVallocator@2@@Z) referenced in function "public: __thiscall mfast::coder::fast_decoder_core<0>::fast_decoder_core<0>(class mfast::allocator *)" (??0?$fast_decoder_core@$0A@@coder@mfast@@QAE@PAVallocator@2@@Z)
18>D:\git\mFAST\build\examples\performance_test\Debug\mf_fixed_decode_v2.exe : fatal error LNK1120: 1 unresolved externals

19>fixed_template_test_v2.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __thiscall mfast::coder::fast_decoder_base::fast_decoder_base(class mfast::allocator *)" (__imp_??0fast_decoder_base@coder@mfast@@QAE@PAVallocator@2@@Z) referenced in function "public: __thiscall mfast::coder::fast_decoder_core<0>::fast_decoder_core<0>(class mfast::allocator *)" (??0?$fast_decoder_core@$0A@@coder@mfast@@QAE@PAVallocator@2@@Z)
19>D:\git\mFAST\build\examples\performance_test\Debug\mf_fixed_decode_encode_v2.exe : fatal error LNK1120: 1 unresolved externals

How to resolve this problem?
Thanks in advance.

**Comment by huangminghuang** [comment]
fix by commit 7515fa38744940845cbd1fd2e3041bd6cf4ed0c1
