### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by JitendraEstee** [objectcomputing/mFAST#78]
when I am trying to integrate mfast with my project, I am getting following error:

/usr/local/include/mfast/int_ref.h: In member function ‘void mfast::int_mref<T>::as(T) const’:
/usr/local/include/mfast/int_ref.h:99:20: error: invalid use of ‘class std::set<T>’
   this->storage()->template set<T>(v);

/usr/local/include/mfast/enum_ref.h: In member function ‘void mfast::enum_mref_ex<Derived, CRefType>::as(mfast::enum_mref_ex<Derived, CRefType>::element_type) const’:
/usr/local/include/mfast/enum_ref.h:159:22: error: invalid use of ‘class std::set<long unsigned int>’
     this->storage()->template set<uint64_t>(v);
                      ^

**Comment by lh18500** [comment]
You must have used namespace std before you include mfast headers. 
The solution is try include mfast headers at the very beginning of your cpp file.
