### ISSUE TITLE
mFAST to decode SBE Fix Bin on CME data

### ISSUE THREAD

**Issue by kirayarmish** [objectcomputing/mFAST#93]
Hello,

I'm wondering if it's possible to decode CME market data with mFAST. On CME they use Simple Binary Encoded messages over FIX Binary (template: ftp://ftp.cmegroup.com/SBEFix/Cert/Templates/templates_FixBinary.xml)?

**Comment by ksergey** [comment]
https://github.com/real-logic/simple-binary-encoding your friend

**Comment by kirayarmish** [comment]
Thanks!
